# app.py
# Streamlit front-end for the EU AI Act Governance Readiness Assessment Tool.
# UI only — no assessment logic lives here. All pipeline logic is in pipeline.py.
#
# Page flow:
#   1. Disclaimer displayed prominently before any form is shown
#   2. Structured input form with character counter on free-text field
#   3. Submit triggers pipeline; result displayed on screen
#   4. User-facing error messages only — no raw exceptions or stack traces

import streamlit as st
from input_handler import AssessmentInput, validate_and_prepare_input, TokenLimitError
from pipeline import run_assessment, ValidationError

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
FREE_TEXT_MAX_CHARS = 3200  # ~800 tokens at conservative chars/3 estimate

DISCLAIMER_TEXT = (
    "--- DISCLAIMER ---\n"
    "This assessment is generated by an AI tool and is provided for informational "
    "purposes only. It does not constitute legal advice, regulatory guidance, or a "
    "compliance determination. Classifications and recommendations are AI-generated "
    "and have not been reviewed by a qualified attorney or compliance professional. "
    "Do not rely on this output as the sole basis for any compliance, product, or "
    "business decision. Consult qualified legal counsel before acting on any findings "
    "in this report.\n"
    "--- END DISCLAIMER ---"
)

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="EU AI Act Governance Readiness Assessment",
    page_icon="⚖️",
    layout="centered",
)

# ---------------------------------------------------------------------------
# Landing disclaimer — must be visible before any form interaction
# ---------------------------------------------------------------------------
st.title("EU AI Act Governance Readiness Assessment")

st.warning(DISCLAIMER_TEXT, icon="⚠️")

st.markdown(
    "This tool helps privacy and legal teams at mid-market organizations understand "
    "their obligations under the EU AI Act. Submit a description of an AI use case "
    "to receive a risk tier classification, applicable obligations, compliance gap "
    "analysis, and a prioritized remediation roadmap."
)

st.divider()

# ---------------------------------------------------------------------------
# Input form
# ---------------------------------------------------------------------------
st.subheader("Describe your AI use case")

with st.form("assessment_form"):
    use_case_name = st.text_input(
        "Use case name",
        placeholder="e.g. AI-powered candidate screening tool",
        max_chars=200,
    )

    industry = st.text_input(
        "Industry",
        placeholder="e.g. Financial Services, Healthcare, Retail",
        max_chars=100,
    )

    deployment_context = st.text_input(
        "Deployment context",
        placeholder="e.g. Internal HR tool used by 3 recruiters, external-facing customer service chatbot",
        max_chars=400,
    )

    current_safeguards = st.text_input(
        "Current safeguards in place",
        placeholder="e.g. Human review of all AI recommendations, opt-out available for customers",
        max_chars=400,
    )

    free_text_description = st.text_area(
        "Description",
        placeholder=(
            "Describe the AI use case in your own words. Include what the system does, "
            "who it affects, what data it uses, and any relevant context about how it "
            "is deployed or governed."
        ),
        height=200,
        max_chars=FREE_TEXT_MAX_CHARS,
    )

    # Character counter displayed below the text area
    chars_used = len(free_text_description)
    chars_remaining = FREE_TEXT_MAX_CHARS - chars_used
    if chars_remaining < 200:
        st.caption(f"⚠️ {chars_remaining} characters remaining (max {FREE_TEXT_MAX_CHARS:,})")
    else:
        st.caption(f"{chars_remaining} characters remaining (max {FREE_TEXT_MAX_CHARS:,})")

    # Pre-submit disclaimer acknowledgment
    st.divider()
    st.markdown("**Before submitting, confirm you have read and understood the disclaimer above.**")
    acknowledged = st.checkbox(
        "I understand this assessment is AI-generated, does not constitute legal advice, "
        "and must be reviewed by qualified legal counsel before any organizational decision is made."
    )

    submitted = st.form_submit_button("Run Assessment", type="primary", use_container_width=True)

# ---------------------------------------------------------------------------
# Submission handling
# ---------------------------------------------------------------------------
if submitted:
    # Gate 1: acknowledgment
    if not acknowledged:
        st.error("Please confirm you have read and understood the disclaimer before submitting.")
        st.stop()

    # Gate 2: required fields
    missing = []
    if not use_case_name.strip():
        missing.append("Use case name")
    if not industry.strip():
        missing.append("Industry")
    if not deployment_context.strip():
        missing.append("Deployment context")
    if not free_text_description.strip():
        missing.append("Description")
    if missing:
        st.error(f"Please complete the following required fields: {', '.join(missing)}")
        st.stop()

    # Gate 3: character limit (belt-and-suspenders — also enforced by max_chars above)
    if chars_used > FREE_TEXT_MAX_CHARS:
        st.error(
            f"Your description is {chars_used:,} characters, which exceeds the {FREE_TEXT_MAX_CHARS:,} "
            "character limit. Please shorten it before submitting."
        )
        st.stop()

    # Build input object and validate token limits
    raw_input = AssessmentInput(
        use_case_name=use_case_name.strip(),
        industry=industry.strip(),
        deployment_context=deployment_context.strip(),
        current_safeguards=current_safeguards.strip(),
        free_text_description=free_text_description.strip(),
    )

    try:
        validated_input = validate_and_prepare_input(raw_input)
    except TokenLimitError:
        st.error(
            "Your submission is too long for the assessment engine to process. "
            "Please shorten your form fields or description and try again."
        )
        st.stop()

    # Run the pipeline
    with st.spinner("Running assessment — this may take 15–30 seconds…"):
        try:
            result = run_assessment(validated_input)
        except ValidationError:
            st.error(
                "Your submission could not be processed. It may be too vague, off-topic, "
                "or not describe a recognizable AI use case. Please revise your description "
                "and try again."
            )
            st.stop()
        except EnvironmentError:
            st.error(
                "The assessment service is not configured correctly. "
                "Please contact support."
            )
            st.stop()
        except Exception:
            st.error(
                "An unexpected error occurred while generating your assessment. "
                "Please try again. If the problem persists, please contact support."
            )
            st.stop()

    # Display result
    st.divider()
    st.subheader("Assessment Result")
    st.markdown(result)
