# pipeline.py
# Two-model agentic pipeline for EU AI Act governance readiness assessment.
#
# Step 1 — Haiku:  Input validation and formatting (no regulatory reasoning)
# Step 2 — Sonnet: Risk classification, regulatory mapping, gap analysis, roadmap
#
# Every output includes the mandatory disclaimer (top and bottom).
# Every API call is logged to api_usage_log.txt (IDs and token counts only, no content).

import os
import datetime
import anthropic
from dotenv import load_dotenv

from config import (
    HAIKU_MODEL,
    SONNET_MODEL,
    MAX_OUTPUT_TOKENS,
    HAIKU_INPUT_COST_PER_1K,
    HAIKU_OUTPUT_COST_PER_1K,
    SONNET_INPUT_COST_PER_1K,
    SONNET_OUTPUT_COST_PER_1K,
    USAGE_LOG_PATH,
)
from input_handler import AssessmentInput, format_for_prompt

load_dotenv(override=True)

# ---------------------------------------------------------------------------
# Mandatory disclaimer — must appear on every output, unmodified
# Source: CLAUDE.md — do not alter this text
# ---------------------------------------------------------------------------
DISCLAIMER = (
    "--- DISCLAIMER ---\n"
    "This assessment is generated by an AI tool and is provided for informational "
    "purposes only. It does not constitute legal advice, regulatory guidance, or a "
    "compliance determination. Classifications and recommendations are AI-generated "
    "and have not been reviewed by a qualified attorney or compliance professional. "
    "Do not rely on this output as the sole basis for any compliance, product, or "
    "business decision. Consult qualified legal counsel before acting on any findings "
    "in this report.\n"
    "--- END DISCLAIMER ---"
)

# ---------------------------------------------------------------------------
# Haiku system prompt — validation and formatting only, no analysis
# ---------------------------------------------------------------------------
HAIKU_SYSTEM = (
    "You are a validation module for an EU AI Act compliance assessment tool.\n\n"
    "Your task:\n"
    "1. Confirm the submitted input describes an actual AI system deployment or planned use case.\n"
    "2. If valid, reformat the input as a clean structured summary (preserve all details, "
    "no analysis, no additions).\n"
    "3. If the input is spam, nonsensical, clearly off-topic, or too vague to classify, "
    "respond with exactly: INVALID: [brief reason]\n\n"
    "If valid, respond with exactly:\n"
    "VALID:\n"
    "[reformatted structured summary]\n\n"
    "Do not add regulatory analysis, risk opinions, or recommendations — those are handled downstream."
)

# ---------------------------------------------------------------------------
# Sonnet system prompt — regulatory reasoning and assessment generation
# ---------------------------------------------------------------------------
SONNET_SYSTEM = (
    "You are an EU AI Act compliance assessment engine. You produce structured governance "
    "readiness assessments for mid-market organizations (100–500 employees) that are "
    "deploying or planning to deploy AI systems.\n\n"
    "You have deep expertise in the EU AI Act (Regulation 2024/1689), including:\n"
    "- Risk tier classification (Unacceptable, High, Limited, Minimal). Note: 'Limited Risk' "
    "is practitioner shorthand — this term does not appear verbatim in the EU AI Act. "
    "It refers to systems subject to transparency obligations under Article 50. Always "
    "clarify this in assessments where Article 50 is the primary classification driver.\n"
    "- Obligations by tier and applicable articles\n"
    "- GPAI obligations under Title VIII\n"
    "- Enforcement timelines and current implementation status\n"
    "- Common compliance gaps for mid-market downstream deployers\n\n"
    "Produce assessments that are accurate, proportionate, and actionable. "
    "Do not overstate risk. Do not understate obligations for high-risk systems. "
    "Flag when article references should be verified against current EUR-Lex text "
    "due to ongoing national implementation guidance. "
    "When Article 50(1) applies and the assessed organization is a downstream deployer "
    "using a third-party AI system: the primary Article 50(1) obligation to disclose AI "
    "interaction rests with the provider who placed the system on the market, not the "
    "deployer. The deployer's primary compliance lever is contractual — requiring the "
    "vendor to build disclosure into the system. Note that Article 26 places independent "
    "obligations on deployers regardless of vendor responsibility — do not imply the "
    "deployer bears no direct compliance obligations. Clearly distinguish provider "
    "obligations from deployer obligations in the assessment output; do not imply the "
    "deployer bears the full Article 50(1) disclosure burden directly.\n"
    "You are not providing legal advice."
)

# ---------------------------------------------------------------------------
# Sonnet user prompt template
# {use_case_summary} is replaced with the Haiku-formatted input
# ---------------------------------------------------------------------------
SONNET_PROMPT_TEMPLATE = """\
Assess the following AI use case under the EU AI Act framework.

{use_case_summary}

Generate a structured assessment using exactly this format. Be concise — keep total response under 500 words:

## RISK TIER
[Unacceptable / High / Limited / Minimal]

**Rationale:** [2–3 sentences citing the relevant EU AI Act provision, annex, or prohibited practice that determines this classification]

## APPLICABLE OBLIGATIONS
List the 3–5 most relevant obligations for this risk tier (include article numbers where applicable):
- [obligation]

## COMPLIANCE GAPS
Based on the current safeguards described, identify 3–5 specific gaps the organization should address:
- [gap]

## REMEDIATION ROADMAP
Prioritized actions (most urgent first, with suggested timelines):
1. [Action] — [Timeline]
2. [Action] — [Timeline]
3. [Action] — [Timeline]

---
Note: Verify all article references against current EUR-Lex text. EU AI Act national implementation guidance is ongoing and may affect specific obligations.\
"""


class ValidationError(Exception):
    """Raised when Haiku rejects the input as invalid or off-topic."""
    pass


def _calculate_cost(input_tokens: int, output_tokens: int, model: str) -> float:
    """Returns estimated cost in USD for a single API call."""
    if model == HAIKU_MODEL:
        return (
            (input_tokens / 1000) * HAIKU_INPUT_COST_PER_1K
            + (output_tokens / 1000) * HAIKU_OUTPUT_COST_PER_1K
        )
    return (
        (input_tokens / 1000) * SONNET_INPUT_COST_PER_1K
        + (output_tokens / 1000) * SONNET_OUTPUT_COST_PER_1K
    )


def _log_usage(
    assessment_id: str,
    model: str,
    step: str,
    input_tokens: int,
    output_tokens: int,
    cost_usd: float,
) -> None:
    """
    Appends one usage record to the local log file.
    Logs assessment_id, token counts, and cost estimate only — never raw content.
    """
    entry = (
        f"{datetime.datetime.utcnow().isoformat()}Z"
        f" | assessment_id={assessment_id}"
        f" | step={step}"
        f" | model={model}"
        f" | input_tokens={input_tokens}"
        f" | output_tokens={output_tokens}"
        f" | cost_usd={cost_usd:.6f}"
        "\n"
    )
    with open(USAGE_LOG_PATH, "a") as f:
        f.write(entry)


def run_assessment(inp: AssessmentInput) -> str:
    """
    Runs the full two-step pipeline for a validated AssessmentInput.

    Returns the complete assessment string with mandatory disclaimer at top and bottom.
    Raises ValidationError if Haiku rejects the input.
    Raises anthropic.APIError on API failures.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key or api_key == "your_api_key_here":
        raise EnvironmentError(
            "ANTHROPIC_API_KEY is not set. Add your key to the .env file."
        )

    client = anthropic.Anthropic(api_key=api_key)
    use_case_text = format_for_prompt(inp)

    # ------------------------------------------------------------------
    # Step 1: Haiku — input validation and formatting
    # ------------------------------------------------------------------
    haiku_response = client.messages.create(
        model=HAIKU_MODEL,
        max_tokens=500,
        system=HAIKU_SYSTEM,
        messages=[{"role": "user", "content": use_case_text}],
    )

    haiku_in = haiku_response.usage.input_tokens
    haiku_out = haiku_response.usage.output_tokens
    haiku_cost = _calculate_cost(haiku_in, haiku_out, HAIKU_MODEL)
    _log_usage(inp.assessment_id, HAIKU_MODEL, "validation", haiku_in, haiku_out, haiku_cost)

    haiku_text = haiku_response.content[0].text.strip()

    if haiku_text.startswith("INVALID:"):
        reason = haiku_text[len("INVALID:"):].strip()
        raise ValidationError(f"Input rejected during validation: {reason}")

    # Strip VALID: prefix; fall back to raw text defensively
    if haiku_text.startswith("VALID:"):
        formatted_input = haiku_text[len("VALID:"):].strip()
    else:
        formatted_input = haiku_text

    # ------------------------------------------------------------------
    # Step 2: Sonnet — classification, mapping, gap analysis, roadmap
    # ------------------------------------------------------------------
    sonnet_prompt = SONNET_PROMPT_TEMPLATE.format(use_case_summary=formatted_input)

    sonnet_response = client.messages.create(
        model=SONNET_MODEL,
        max_tokens=MAX_OUTPUT_TOKENS,
        system=SONNET_SYSTEM,
        messages=[{"role": "user", "content": sonnet_prompt}],
    )

    sonnet_in = sonnet_response.usage.input_tokens
    sonnet_out = sonnet_response.usage.output_tokens
    sonnet_cost = _calculate_cost(sonnet_in, sonnet_out, SONNET_MODEL)
    _log_usage(inp.assessment_id, SONNET_MODEL, "assessment", sonnet_in, sonnet_out, sonnet_cost)

    # ------------------------------------------------------------------
    # Assemble final output — disclaimer at top AND bottom (per CLAUDE.md)
    # ------------------------------------------------------------------
    total_input_tokens = haiku_in + sonnet_in
    total_output_tokens = haiku_out + sonnet_out
    total_cost = haiku_cost + sonnet_cost

    assessment_text = sonnet_response.content[0].text.strip()

    output = "\n".join([
        DISCLAIMER,
        "",
        "=" * 60,
        "EU AI ACT GOVERNANCE READINESS ASSESSMENT",
        f"Assessment ID : {inp.assessment_id}",
        f"Generated     : {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
        "=" * 60,
        "",
        assessment_text,
        "",
        "=" * 60,
        f"Token usage  —  Input: {total_input_tokens}  |  Output: {total_output_tokens}  |  "
        f"Estimated cost: ${total_cost:.4f}",
        "=" * 60,
        "",
        DISCLAIMER,
    ])

    return output
